# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - apireabilitate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-front-end:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies for Angular
        run: |
          cd client/Identity.WebAPI/
          npm install -g @angular/cli
          npm install

    # Rodar o build do Angular (para produção)
      - name: Build Angular app
        run: |
          cd client/Identity.WebAPI/
          ng build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .angular-app
          path: client/Identity.WebAPI/dist/identity.web-api/browser

  build-back-end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish server/Identity.webapi/Identity.webapi.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  trivy-scan-back-end:
    runs-on: ubuntu-latest
    needs:  build-back-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.40.0_Linux-64bit.deb
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
          sudo cp html.tpl /usr/bin/html.tpl

      - name: Run Trivy scan on Docker back-end image
        run: |
          docker build -t identity .
          trivy image --format template --template "@/usr/bin/html.tpl" -o trivy-report.html identity

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report-back-end
          path: trivy-report.html

  trivy-scan-front-end:
    runs-on: ubuntu-latest
    needs: build-front-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.40.0_Linux-64bit.deb
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
          sudo cp html.tpl /usr/bin/html.tpl

      - name: Run Trivy scan on Docker front-end image
        run: |
          docker build -t identity client/Identity.WebAPI
          trivy image --format template --template "@/usr/bin/html.tpl" -o trivy-report.html identity

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report-front-end
          path: trivy-report.html

  unit-test-front-end:
    runs-on: ubuntu-latest
    needs: trivy-scan-front-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies for Angular
        run: |
          cd client/Identity.WebAPI/
          npm install -g @angular/cli
          npm install

      - name: Run Angular tests
        run: |
          cd client/Identity.WebAPI/
          ng test --watch=false --browsers=ChromeHeadless --code-coverage
          
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: angular-coverage-report
          path: client/Identity.WebAPI//coverage/

  arc-tests:
    runs-on: ubuntu-latest
    needs: trivy-scan-back-end
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Run Unit tests
        run: |
          dotnet test tests/Identity.ArchUnit.Tests/Identity.ArchUnit.Tests.csproj
          
  unit-tests-back-end:
    runs-on: ubuntu-latest
    needs: arc-tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Unit tests
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet test tests/Identity.Unit.Tests/Identity.Unit.Tests.csproj --verbosity minimal --collect:"XPlat Code Coverage"

      - name: Generate Unit test report
        if: always()
        run: |
          reportgenerator "-reports:**/**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
          cd tests/Identity.Unit.Tests/

      - name: Upload Unit test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-test-results
          path: coveragereport/
          
  Stryker-tests-back-end:
    runs-on: ubuntu-latest
    needs: unit-tests-back-end
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Generate Stryker report
        if: always()
        run: |
          cd tests/Identity.Unit.Tests/
          dotnet tool install --global dotnet-stryker
          dotnet test 
          dotnet-stryker -l complete

      - name: List files
        if: always()
        run: |
          echo "Arquivos:"
          ls -R

      - name: Upload dotnet-stryker results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dotnet-stryker-results
          path: ./tests/Identity.Unit.Tests/StrykerOutput

  integration-tests:
    runs-on: ubuntu-latest
    needs: Stryker-tests-back-end
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Integration tests
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet test tests/Identity.Intagration.Tests/Identity.Intagration.Tests.csproj --verbosity minimal --collect:"XPlat Code Coverage"
          reportgenerator "-reports:**/**/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html

      - name: Upload Integration tests results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: integration-tests-results
          path: coveragereport/

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [integration-tests, unit-test-front-end]
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          include-prerelease: true

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verifica se o Docker Compose foi instalado corretamente

      - name: Run E2E tests
        run: |
          dotnet test tests/Identity.SpecFlow.Tests/Identity.SpecFlow.Tests.csproj \
          --logger "trx;LogFileName=test-results.trx" # Gerando arquivo de resultados no formato TRX

      - name: Upload E2E test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-tests-results
          path: tests/Identity.SpecFlow.Tests/TestResults/test-results.trx

      - name: Living Docs HTML
        if: always()
        run: |
          dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
          livingdoc test-assembly tests/Identity.SpecFlow.Tests/bin/Debug/net6.0/Identity.SpecFlow.Tests.dll -t tests/Identity.SpecFlow.Tests/bin/Debug/net6.0/TestExecution.json --project-language pt-br

      - name: Upload Living Docs results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-tests-LivingDocs-results
          path: LivingDoc.html

  benchmark-tests:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verifica se o Docker Compose foi instalado corretamente

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Run Benchmark tests
        run: |
          dotnet run --project tests/Identity.Benchmark.Tests/Identity.Benchmark.Tests.csproj -c Release

      - name: Publish Benchmark results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: benchmark-tests-results
          path: BenchmarkDotNet.Artifacts/

  deploy-back-end:
    runs-on: ubuntu-latest
    needs: benchmark-tests
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apireabilitate'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_87F529B45A86452A86399270218E26CD }}
          package: .
